// AGENT_MANAGED: generated by tools/remotion_runner.py before each render.
// Do not edit by hand - this file is regenerated on every assemble and is the
// single source of truth for scene timing, transitions, and overlays.
export type VisualType = 'photo' | 'text_card';

export interface SceneRenderConfig {
	index: number;
	audioDuration: number;
	baseDurationInFrames: number;
	textOverlay: string;
	visualType: VisualType;
	delivery: string;
}

export const FPS = 30;
export const PADDING_FRAMES = 3;
export const TRANSITION_FRAMES = 10;
export const HAS_BGM = true;
export const TRANSITIONS: string[] = ["fade", "fade", "fade", "fade"];
export const SCENES: SceneRenderConfig[] = [
  {index: 0, audioDuration: 4.176, baseDurationInFrames: 129, textOverlay: "Lost deal", visualType: "photo", delivery: "fast_punchy"},
  {index: 1, audioDuration: 7.464, baseDurationInFrames: 227, textOverlay: "Verbal agreement made", visualType: "photo", delivery: "warm_confident"},
  {index: 2, audioDuration: 10.608, baseDurationInFrames: 322, textOverlay: "Misunderstanding arises", visualType: "photo", delivery: "slow_emphatic"},
  {index: 3, audioDuration: 9.576, baseDurationInFrames: 291, textOverlay: "Written agreement prevents issues", visualType: "photo", delivery: "warm_confident"},
  {index: 4, audioDuration: 3.648, baseDurationInFrames: 113, textOverlay: "PayTrustGH.com", visualType: "text_card", delivery: "fast_punchy"}
];
export const TOTAL_DURATION_IN_FRAMES = 1082;
