// AGENT_MANAGED: generated by tools/remotion_runner.py before each render.
// Do not edit by hand - this file is regenerated on every assemble and is the
// single source of truth for scene timing, transitions, and overlays.
export type VisualType = 'photo' | 'text_card';

export interface SceneRenderConfig {
	index: number;
	audioDuration: number;
	baseDurationInFrames: number;
	textOverlay: string;
	visualType: VisualType;
	delivery: string;
}

export const FPS = 30;
export const PADDING_FRAMES = 3;
export const TRANSITION_FRAMES = 10;
export const HAS_BGM = true;
export const TRANSITIONS: string[] = ["fade", "fade", "fade", "fade"];
export const SCENES: SceneRenderConfig[] = [
  {index: 0, audioDuration: 9.264, baseDurationInFrames: 281, textOverlay: "5 GHS Jerseys Promo", visualType: "photo", delivery: "fast_punchy"},
  {index: 1, audioDuration: 7.2, baseDurationInFrames: 219, textOverlay: "Step 1: Create Account", visualType: "photo", delivery: "neutral"},
  {index: 2, audioDuration: 22.44, baseDurationInFrames: 677, textOverlay: "Step 2: Reply With Screenshots", visualType: "photo", delivery: "neutral"},
  {index: 3, audioDuration: 3.816, baseDurationInFrames: 118, textOverlay: "Winners Before Every Ghana Game", visualType: "photo", delivery: "warm_confident"},
  {index: 4, audioDuration: 5.4, baseDurationInFrames: 165, textOverlay: "CollectiblesGH.com", visualType: "text_card", delivery: "fast_punchy"}
];
export const TOTAL_DURATION_IN_FRAMES = 1460;
