"""
Remotion runner: writes the generated render config consumed by the Remotion
template (single source of truth) and triggers the Remotion CLI render.

Phase 0 of the upgrade plan removed the previous regex patching of TSX source.
Instead this module generates ``templates/MarketingVideo/src/video-config.ts``,
which both ``Root.tsx`` and ``MarketingVideo.tsx`` import. Nothing in the TSX is
rewritten in place anymore.
"""

import os
import json
import logging
import subprocess
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()
logger = logging.getLogger(__name__)

from agents.asset_builder import FPS, PADDING_FRAMES, TRANSITION_FRAMES, layout_for_scene
from tools import frame_math

TEMPLATE_DIR = Path(__file__).parent.parent / "templates" / "MarketingVideo"
VIDEO_CONFIG_PATH = TEMPLATE_DIR / "src" / "video-config.ts"

# Every boundary always carries a transition so the frame math stays consistent;
# unknown names fall back to fade rather than dropping the transition.
VALID_TRANSITIONS = {"fade", "slide", "wipe", "flip", "clockWipe"}
DEFAULT_TRANSITION = "fade"


def _ordered_scenes(config: dict) -> list[dict]:
    """Scenes from the embedded brief, sorted by scene_number (render order)."""
    brief = config.get("brief") or {}
    scenes = brief.get("scenes") or []
    return sorted(
        (s for s in scenes if isinstance(s, dict)),
        key=lambda s: s.get("scene_number", 0),
    )


def _resolve_transitions(config: dict, n_boundaries: int) -> list[str]:
    """Per-boundary transition names; defaults to fade. Invalid names fall back to fade."""
    raw = config.get("transitions")
    out: list[str] = []
    for i in range(n_boundaries):
        name = DEFAULT_TRANSITION
        if isinstance(raw, list) and i < len(raw):
            candidate = str(raw[i]).strip()
            if candidate in VALID_TRANSITIONS:
                name = candidate
            else:
                logger.warning("Unknown transition %r at boundary %d; using %s", raw[i], i, DEFAULT_TRANSITION)
        out.append(name)
    return out


def write_render_config(config: dict, has_bgm: bool = True) -> int:
    """
    Write ``src/video-config.ts`` from the assembler config and return total frames.

    The generated module is the only timing/overlay source the Remotion template
    reads. Scene durations, transition tails, text overlays, and visual types all
    flow through here.
    """
    durations: list[float] = list(config.get("durations") or [])
    if not durations:
        raise ValueError("write_render_config: config has no durations")

    scenes = _ordered_scenes(config)
    if len(scenes) != len(durations):
        # Durations are authoritative for timing; pad/truncate overlay metadata to match.
        logger.warning(
            "Scene count (%d) != duration count (%d); aligning by index",
            len(scenes),
            len(durations),
        )

    base_frames = frame_math.base_frames_for_durations(durations, FPS, PADDING_FRAMES)
    total_frames = frame_math.total_composition_frames(durations, FPS, PADDING_FRAMES)
    transitions = _resolve_transitions(config, max(0, len(durations) - 1))

    scene_entries = []
    for idx, (dur, base) in enumerate(zip(durations, base_frames)):
        scene = scenes[idx] if idx < len(scenes) else {}
        text_overlay = str(scene.get("text_overlay", "") or "")
        # Invariant I5: visualType is derived from scene index here, NOT read from
        # the brief's visual_type field (which is inert metadata). This is the
        # single source of layout authority for the renderer.
        visual_type = layout_for_scene(idx)
        delivery = str(scene.get("delivery", "neutral") or "neutral")
        scene_entries.append(
            {
                "index": idx,
                "audioDuration": round(float(dur), 3),
                "baseDurationInFrames": int(base),
                "textOverlay": text_overlay,
                "visualType": visual_type,
                "delivery": delivery,
            }
        )

    scene_lines = ",\n".join(
        "  {{index: {index}, audioDuration: {audio}, baseDurationInFrames: {base}, "
        "textOverlay: {text}, visualType: {vt}, delivery: {delivery}}}".format(
            index=e["index"],
            audio=e["audioDuration"],
            base=e["baseDurationInFrames"],
            text=json.dumps(e["textOverlay"], ensure_ascii=False),
            vt=json.dumps(e["visualType"]),
            delivery=json.dumps(e["delivery"]),
        )
        for e in scene_entries
    )
    transitions_literal = ", ".join(json.dumps(t) for t in transitions)

    content = f"""// AGENT_MANAGED: generated by tools/remotion_runner.py before each render.
// Do not edit by hand - this file is regenerated on every assemble and is the
// single source of truth for scene timing, transitions, and overlays.
export type VisualType = 'photo' | 'text_card';

export interface SceneRenderConfig {{
\tindex: number;
\taudioDuration: number;
\tbaseDurationInFrames: number;
\ttextOverlay: string;
\tvisualType: VisualType;
\tdelivery: string;
}}

export const FPS = {FPS};
export const PADDING_FRAMES = {PADDING_FRAMES};
export const TRANSITION_FRAMES = {TRANSITION_FRAMES};
export const HAS_BGM = {str(bool(has_bgm)).lower()};
export const TRANSITIONS: string[] = [{transitions_literal}];
export const SCENES: SceneRenderConfig[] = [
{scene_lines}
];
export const TOTAL_DURATION_IN_FRAMES = {total_frames};
"""

    VIDEO_CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    VIDEO_CONFIG_PATH.write_text(content, encoding="utf-8")
    logger.info(
        "Wrote %s: %d scenes, %d total frames (%.1fs), transitions=%s, has_bgm=%s",
        VIDEO_CONFIG_PATH.name,
        len(scene_entries),
        total_frames,
        total_frames / FPS,
        transitions,
        has_bgm,
    )
    return total_frames


def copy_assets_to_public(scene_images: list[str], audio_files: list[str], bgm_path: str | None = None):
    """Copy generated scene images, audio files, and BGM into Remotion's public/ dir."""
    import shutil

    scenes_dir = TEMPLATE_DIR / "public" / "scenes"
    audio_dir = TEMPLATE_DIR / "public" / "audio"
    scenes_dir.mkdir(parents=True, exist_ok=True)
    audio_dir.mkdir(parents=True, exist_ok=True)

    for img_path in scene_images:
        dest = scenes_dir / os.path.basename(img_path)
        shutil.copy2(img_path, dest)
        logger.info("Copied image: %s -> %s", img_path, dest)

    for aud_path in audio_files:
        dest = audio_dir / os.path.basename(aud_path)
        shutil.copy2(aud_path, dest)
        logger.info("Copied audio: %s -> %s", aud_path, dest)

    if bgm_path and os.path.exists(bgm_path):
        dest = audio_dir / "bgm.mp3"
        shutil.copy2(bgm_path, dest)
        logger.info("Copied BGM: %s -> %s", os.path.basename(bgm_path), dest)


def render_video(output_path: str) -> str:
    """Run Remotion CLI to render the final MP4."""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    cmd = [
        "npx", "remotion", "render",
        "MarketingVideo", output_path,
        "--codec=h264", "--crf=23",
    ]
    logger.info("Rendering: %s", " ".join(cmd))

    result = subprocess.run(
        cmd,
        cwd=str(TEMPLATE_DIR),
        capture_output=True,
        timeout=600,
        shell=True,
        encoding="utf-8",
        errors="replace",
    )

    if result.returncode != 0:
        logger.error("Render FAILED:\nstdout: %s\nstderr: %s", result.stdout, result.stderr)
        raise RuntimeError(f"Remotion render failed: {result.stderr[-500:]}")

    if not os.path.exists(output_path):
        raise RuntimeError(f"Render produced no output at: {output_path}")

    file_size = os.path.getsize(output_path)
    if file_size < 100_000:
        raise RuntimeError(f"Output file suspiciously small: {file_size} bytes")

    logger.info("Render complete: %s (%.1f MB)", output_path, file_size / 1_048_576)
    return output_path


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    test_config = {
        "durations": [6.5, 8.2, 7.1, 8.5, 6.0],
        "transitions": ["fade", "wipe", "slide", "fade"],
        "brief": {
            "scenes": [
                {"scene_number": i, "text_overlay": f"Overlay {i}", "visual_type": "photo", "delivery": "neutral"}
                for i in range(5)
            ]
        },
    }
    frames = write_render_config(test_config)
    print(f"Wrote video-config.ts with test durations. Total frames: {frames}")
